# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean verify --file se.bitcraze.crazyflie.ect.bootloader-parent/pom.xml
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 'ECT Bootloader repository'
        path: se.bitcraze.crazyflie.ect.bootloader-repository/target/se.bitcraze.crazyflie.ect.bootloader-repository-*.zip
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: se.bitcraze.crazyflie.ect.bootloader/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
